---
abstract: 'fuzzy role constraints'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Class::Tiny: 0
  Role::Tiny: 1.000000
  Test::More: 0.96
  Test::TypeTiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-Interface
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Types::Interface:
    file: lib/Types/Interface.pm
    version: 0.002
requires:
  Role::Inspector: 0
  Type::Library: 0
  Types::LoadableClass: 0
  Types::Standard: 0
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Types-Interface/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-Interface
  homepage: https://metacpan.org/release/Types-Interface
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-types-interface.git
version: 0.002
